### PR TITLE
Fix dependency parsing, allow space inside parameter list

### PR DESCRIPTION
**Pull request by jzaefferer**
Signed-off-by: Jörn Zaefferer joern.zaefferer@gmail.com

### CODE REVIEW

**Comment by jzaefferer** [comment]
Need this to make (new) tests on download builder pass. Maybe give me push access to the git repo and make me an owner for the npm package? Then I could handle this myself.

**Comment by rxaviers** [comment]
Interestingly I have just done it and saw your comment asking for it :stuck_out_tongue_closed_eyes:

**Comment by rxaviers** [comment]
I've included you and @arschmitz

**Comment by rxaviers** [comment]
LGTM :+1:

**Comment by arschmitz** [comment]
looks good to me too and @rxaviers thank you

**Comment by jzaefferer** [comment]
Merged and released as 0.0.4.

**Pull request merged**
